In [21]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
df = pd.read_csv('recipe_site_traffic_2212.csv')

df.high_traffic = df.high_traffic.fillna('Not High')
df['category'] = df['category'].replace('Chicken Breast', 'Chicken')
df['servings'] = df['servings'].str.replace(' as a snack', '').astype(int)

def fill_missing(cat):
    df[cat] = df.groupby('category')[cat].transform(lambda x: x.fillna(x.median()))

for x in ['calories', 'carbohydrate', 'sugar', 'protein']:
    fill_missing(x)
df.isna().sum()


# encode high_traffic , High = 1
df['high_traffic'] = df['high_traffic'].map({'High': 1, 'Not High': 0})

# One hot encode
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder object
encoder = OneHotEncoder()
# Fit and transform the "category" column
encoded_categories = encoder.fit_transform(df[['category']])
# Create a DataFrame with the encoded categories
encoded_df = pd.DataFrame(encoded_categories.toarray(), columns=encoder.categories_[0])
# Concatenate the original DataFrame with the encoded DataFrame
df_encoded = pd.concat([df, encoded_df], axis=1)
# Drop columns
df_encoded.drop(['category','Vegetable','recipe'], axis=1, inplace=True)
# Print the encoded data
df_encoded.head()

,calories,carbohydrate,sugar,protein,servings,high_traffic,Beverages,Breakfast,Chicken,Dessert,Lunch/Snacks,Meat,One Dish Meal,Pork,Potato
0,399.26,19.56,5.23,29.82,6,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,35.48,38.56,0.66,0.92,4,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,914.28,42.68,3.09,2.88,1,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,97.03,30.56,38.63,0.02,4,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,27.05,1.85,0.80,0.53,4,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
features = df_encoded.drop('high_traffic', axis = 1)
target = df_encoded['high_traffic']

# Import the function for splitting dataset into train and test
from sklearn.model_selection import train_test_split

# Use that function to create the splits both for target and for features
target_train, target_test, features_train, features_test = train_test_split(target,features,test_size=0.25,random_state=42)

In [23]:
df.high_traffic.value_counts()/len(df)

1    0.606125
0    0.393875
Name: high_traffic, dtype: float64

In [24]:
df.head()

,recipe,calories,carbohydrate,sugar,protein,category,servings,high_traffic
0,1,399.26,19.56,5.23,29.82,Pork,6,1
1,2,35.48,38.56,0.66,0.92,Potato,4,1
2,3,914.28,42.68,3.09,2.88,Breakfast,1,0
3,4,97.03,30.56,38.63,0.02,Beverages,4,1
4,5,27.05,1.85,0.80,0.53,Beverages,4,0

In [ ]:
temp.columns = ['department', 'churn', 'prop']
temp.prop = temp.prop.mul(100)
temp = temp[temp.churn == "yes"]
temp = temp.sort_values("prop", ascending=False).reset_index()
temp

In [28]:




test = df.groupby('high_traffic')['category'].value_counts()
test

high_traffic  category
0             Chicken          99
              Beverages        87
              Breakfast        73
              Lunch/Snacks     32
              Dessert          30
              Meat             20
              One Dish Meal    19
              Pork              7
              Potato            5
              Vegetable         1
1             Potato           83
              Vegetable        82
              Pork             77
              Chicken          73
              Meat             59
              Lunch/Snacks     57
              Dessert          53
              One Dish Meal    52
              Breakfast        33
              Beverages         5
Name: category, dtype: int64

In [27]:
test = pd.DataFrame(test).reset_index()

ValueError: cannot insert category, already exists